### ISSUE TITLE
هەڵەکانی دەقی کراس زەردێ، ڕەزا بابامیری

### ISSUE THREAD

**Issue by allekok** [KurdishBLARK/KurdishLyricsCorpus#1]
کەوێ ساوا -> کە وێساوە
یان
کەوێ ساوا -> کە وێستاوە
https://github.com/KurdishBLARK/KurdishLyricsCorpus/blob/0135834bf9f44b7a0eb1a3f12b659f045991e48b/KurdishLyricsCorpus.xml#L113
دەستپێکەری -> دەس پێشکەری
https://github.com/KurdishBLARK/KurdishLyricsCorpus/blob/0135834bf9f44b7a0eb1a3f12b659f045991e48b/KurdishLyricsCorpus.xml#L115
ئێستە دەیبینم کە ئەو عەهدی لەبیر بردۆتەوە
https://github.com/KurdishBLARK/KurdishLyricsCorpus/blob/0135834bf9f44b7a0eb1a3f12b659f045991e48b/KurdishLyricsCorpus.xml#L126
ئەو گڕەی بۆ من لە دڵیا بوو هەمووی نیشتۆتەوە
https://github.com/KurdishBLARK/KurdishLyricsCorpus/blob/0135834bf9f44b7a0eb1a3f12b659f045991e48b/KurdishLyricsCorpus.xml#L127
وەک نە بای دیبێ نە بۆران گشتی هەر لەبیر چۆتەوە
https://github.com/KurdishBLARK/KurdishLyricsCorpus/blob/0135834bf9f44b7a0eb1a3f12b659f045991e48b/KurdishLyricsCorpus.xml#L128
دەردێنم -> دەرهێنام
https://github.com/KurdishBLARK/KurdishLyricsCorpus/blob/0135834bf9f44b7a0eb1a3f12b659f045991e48b/KurdishLyricsCorpus.xml#L132
سەرچاوەکەم پی‌دی‌افی دیوانی مەدهۆشە:
https://github.com/allekok/diwan/raw/master/%D9%85%DB%95%D8%AF%D9%87%DB%86%D8%B4%20-%20%DB%8C%D8%A7%D9%86%DB%95%DB%8C%20%D8%AF%DA%B5%D8%A7%D9%86.pdf
شێعری "بێ وەفایی" مەدهۆش: https://allekok.ir/poet:85/book:1/poem:15

**Comment by sinaahmadi** [comment]
زۆر سپاس بۆ پێداچوونەوەکانت.
هەڵەکان ڕاست کرانەوە.
